openapi: "3.0.0"
info:
  title: full fledged tshirt store API
  description: LCO - a course to create API for ecomm store
  version: 1.0.1
  contact:
    email: bedisanam@gmail.com
    url: "asiangiftcentre.com"

# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: for localhost -regular
#   - url: "https://localhost:4000/api/v1"
#     description: for localhost -secure

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for localhost
    variables: 
      version:
        enum:
          - v1
          - v2
        default: v1  
      protocol:
        enum:
          - http
          - https
        default: http  

components: 
  securitySchemes:     
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http       
      scheme: bearer

paths:
  /dummy: 
    get:
      tags:
        - Home
      summary: returns a greet message from LCO
      responses: 
        200:
          description: All Good and successful
          content:
            application/json:
              schema: 
                type: string
                example: "MyString"
        400:
          description: "Bad Request"      
        500:
          description: "Internal Server Error"      